### ISSUE TITLE
Slow perfs

### ISSUE THREAD

**Issue by AlexGalays** [esnext/es6-arrow-function#2]
Hello,

I would like to use es6-arrow-function but it makes my build 10 times slower and make it unsuitable for the fast compilation/live reloading combo.

I realize the full AST has to be built and it can't be very fast but is there anything that can be done?

Cheers

**Comment by stefanpenner** [comment]
@AlexGalays perform the transformation only the file that changed.

**Comment by AlexGalays** [comment]
Seems like a good idea indeed.

**Comment by AlexGalays** [comment]
Actually, if I manually compile all the files one by one, it is much faster (and fast enough not to require incremental compilation) than when using es6-arrow-function as a browserify transform. So I guess the problem lies on browserify's side.

**Comment by eventualbuddha** [comment]
Odd. Thanks for following up on that, @AlexGalays. I'm sure the browserify folks would be happy to see a bit of perf. data if you can put together a slower-than-expected use case with some profiling.
