### ISSUE TITLE
Avoid adding extra newlines to compilation result

### ISSUE THREAD

**Issue by spion** [esnext/es6-arrow-function#3]
This would result with the preservation of correct line numbers in stack traces without the need to generate full-blown source maps.

Is something like this possible using recast?

**Comment by eventualbuddha** [comment]
This suggests that there should be a way to do it:

``` js
~ echo 'var foo = () => 42;' | es6-arrow-function
var foo = function() {
  return 42;
};
~ echo 'var foo = () => { 42 };' | es6-arrow-function
var foo = function() { 42 };
```

Pull requests welcome!

**Comment by spion** [comment]
Thanks, I'll give it a try! :P

Edit: I [figured out the reason](https://github.com/benjamn/recast/blob/eb8c1a0b934e0097f754337ba207472642ad64a3/lib/printer.js#L395-L398). I guess this is not exactly configurable, unfortunately.

**Comment by rainbow-alex** [comment]
I worked around this by reprinting without recast. It's not a very elegant solution, but it seems to work.

https://github.com/rainbow-alex/afnc/blob/master/afnc.js#L162
https://github.com/rainbow-alex/afnc/blob/master/afnc.js#L181

**Comment by eventualbuddha** [comment]
Closing this as there's not really much we can do about it without changing recast.
